import Head from "next/head";
import Link from "next/link";
import DataTable from "../components/DataTable";
import { getTransferData } from "~/lib/transferData";
import { TransferDataType } from "~/lib/types";
import { useState } from "react";

// const mockData = [
//   {
//     treeAuthority: "ABC123",
//     transferCount: 2,
//   },
//   {
//     treeAuthority: "DEF456",
//     transferCount: 1,
//   },
//   {
//     treeAuthority: "GHI789",
//     transferCount: 0,
//   },
//   {
//     treeAuthority: "JKL012",
//     transferCount: 3,
//   },
//   {
//     treeAuthority: "MNO345",
//     transferCount: 1,
//   },
// ];

const Home = (props: { transferData: TransferDataType[] }) => {
  const [data, setData] = useState<TransferDataType[]>(props.transferData);

  return (
    <>
      <Head>
        <title>Carpool Take Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-zinc-900 font-mono">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16">
          <p className="text-sm text-white md:text-lg">Program</p>
          <h1 className="text-5xl font-bold tracking-tight text-white sm:text-[5rem]">
            Bubblegum
          </h1>
          <p className="text-sm text-white md:text-lg">
            BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY
          </p>
        </div>
        <div className="flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-[3rem]">
            Tree Authority Accounts
          </h2>
          <p className="text-sm text-white md:text-lg">
            Displaying the top 100 tree authority accounts by number of
            transfers in the last 24 hours.
          </p>
        </div>
        <DataTable data={data} />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const transferData = await getTransferData();
  return {
    props: {
      transferData: transferData,
    },
  };
}

export default Home;
