import { useState } from "react";
import Head from "next/head";
import DataTable from "../components/DataTable";
import { getTransferData } from "~/lib/transferData";
import { TransferDataType } from "~/lib/types";

/*
 * Thanks for taking the time to review my code!
 * I've written this using certain elements of the T3 Stack,
 * specifically Next.js, TypeScript, and Tailwind CSS.
 *
 * To run this locally, just run an `npm install` and then `npm run dev`.
 * You will also need to create a .env file with an appropriate API_KEY.
 *
 * It is deployed to Vercel at https://carpool-takhome.vercel.app/.
 */

const Home = (props: { transferData: TransferDataType[] }) => {
  const [data, setData] = useState<TransferDataType[]>(props.transferData);

  return (
    <>
      <Head>
        <title>Carpool Take Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-zinc-900 font-mono">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16">
          <p className="text-sm text-white md:text-lg">Program</p>
          <h1 className="text-5xl font-bold tracking-tight text-white sm:text-[5rem]">
            Bubblegum
          </h1>
          <p className="text-sm text-white md:text-lg">
            BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY
          </p>
        </div>
        <div className="flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-[3rem]">
            Tree Authority Accounts
          </h2>
          <p className="text-sm text-white md:text-lg">
            Displaying the top 100 tree authority accounts by number of
            transfers in the last 24 hours.
          </p>
        </div>
        <DataTable data={data} />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const transferData = await getTransferData();
  return {
    props: {
      transferData: transferData,
    },
  };
}

export default Home;
